//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MagicKD.rc
//
#define IDD_MAGICKD                     101
#define IDD_MAGICKD_END                 102
#define IDD_MAGICKD_CONFIG              103
#define IDD_MAGICKD_WALLCHANGER         104
#define IDR_MAINFRAME                   121
#define IDS_SEL_FOLDER                  131
#define IDS_TRAY_CLOSEWINDOW            141
#define IDS_TRAY_RANDPIC                142
#define IDS_TRAY_DELNOWPIC              143
#define IDS_TRAY_OPENWINDOW             144
#define IDS_TRAY_WALLCHANGER            145
#define IDS_CONF_STATIC_TRANSPARENCY    151
#define IDS_CONF_CHECK_STARTMIN         152
#define IDS_CONF_CHECK_SHOWCLOSEWINDOW  153
#define IDS_WALL_COLUMN_CLASSLIST       161
#define IDS_WALL_COLUMN_DIRPATH         162
#define IDS_WALL_COLUMN_PICFINDNUM      163
#define IDS_WALL_BTN_ENABLETIP          171
#define IDS_WALL_BTN_DISABLETIP         172
#define IDS_WALL_BTN_RANDPIC            173
#define IDS_WALL_BTN_DELPIC             174
#define IDS_WALL_BTN_ADDCLASS           176
#define IDS_WALL_CHECK_SHOWDIRLOADERROR 177
#define IDS_WALL_STATIC_CACHEDNUM       181
#define IDS_WALL_STATIC_WAITTIME        182
#define IDS_WALL_STATIC_PICTOTALNUM     183
#define IDS_WALL_MENU_ADDENABLECLASSLIST 191
#define IDS_WALL_MENU_DELCLASSLIST      192
#define IDS_WALL_MENU_ADDDIRPATH        193
#define IDS_WALL_MENU_UPDATEDIRFILEFIND 194
#define IDS_WALL_MENU_DELDIRPATH        195
#define IDS_WALL_MENU_UPDATEALLDIRFILEFIND 196
#define IDS_WALL_TOOLTIP_RANDPIC        201
#define IDS_WALL_TOOLTIP_DELNOWPIC      202
#define IDS_WALL_TOOLTIP_SETWAITTIME    203
#define IDS_WALL_TOOLTIP_SETHISTORYNUM  204
#define IDS_WALL_TOOLTIP_SETCACHEPICNUM 205
#define IDS_WALL_TOOLTIP_ADDCLASS       206
#define IDS_WALL_TOOLTIP_CLASSLIST      207
#define IDS_WALL_TOOLTIP_DIRLIST        208
#define IDS_WALL_TOOLTIP_IMAGELOADERROR 209
#define IDS_WALL_CANONLYCHOICEONECLASS  211
#define IDS_WALL_DIRNOTEXIST            212
#define IDS_WALL_DIRNOTEXIST_ONNOTFIXEDDRIVE 213
#define IDS_WALL_DIRNOTEXIST_UPDATEPATHLATER 214
#define IDS_WALL_SETWALLPAGERFAIL       215
#define IDS_WALL_SETTINGWALLPAGER       216
#define IDS_WALL_MSG_IMAGELOADERROR     217
#define IDS_WALL_COMBOX_ASKUSER         221
#define IDS_WALL_COMBOX_DELETE          222
#define IDS_WALL_COMBOX_EXPLORE         223
#define IDS_WALL_COMBOX_NULL            224
#define IDS_WALL_COMBOX_ASKDELETE       235
#define IDC_TAB_MAIN                    1000
#define IDC_PROGRESS_END                1001
#define IDC_MAGICKDEND_EDIT_TEXT        1002
#define IDC_CONF_CHECK_STARTMIN         1003
#define IDC_CONF_CHECK_WALLCHANGER      1004
#define IDC_CONF_SLIDER_TRANSPARENCY    1005
#define IDC_CONF_STATIC_TRANSPARENCY    1006
#define IDC_COMBO_IMAGELOADERROR        1009
#define IDC_WALL_COMBO_IMAGELOADERROR   1009
#define IDC_WALL_STATIC_RESTTIME        1011
#define IDC_WALL_STATIC_NOWPICPATH      1012
#define IDC_CONF_CHECK_SHOWCLOSEWINDOW  1012
#define IDC_WALL_STATIC_CACHENUM        1013
#define IDC_WALL_STATIC_CACHEDNUM       1014
#define IDC_WALL_STATIC_WAITTIME        1015
#define IDC_WALL_CHECK_SHOWDIRLOADERROR 1016
#define IDC_WALL_STATIC_PICTOTALNUMSHOW 1017
#define IDC_WALL_STATIC_PICTOTALNUM     1018
#define IDC_WALL_BTN_ADDCLASS           1021
#define IDC_WALL_BTN_RANDPIC            1022
#define IDC_WALL_BTN_DELPIC             1023
#define IDC_WALL_BTN_ENABLETOOLTIP      1024
#define IDC_WALL_LIST_CLASS             1031
#define IDC_WALL_LIST_DIRPATH           1032
#define IDC_WALL_EDIT_WAITTIME          1041
#define IDC_WALL_EDIT_ADDCLASS          1042
#define IDC_WALL_EDIT_HISTORYNUM        1043
#define IDC_WALL_EDIT_CACHENUM          1044

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
